### ISSUE TITLE
Cannot install pod!!

### ISSUE THREAD

**Issue by umarchohan** [nicol3a/NBBottomSheet#1]
I can't install the pods[
<img width="563" alt="Screen Shot 2019-05-10 at 4 07 49 PM" src="https://user-images.githubusercontent.com/4208645/57553861-cf527e00-733d-11e9-8920-5aa3914735e8.png">
](url)

**Comment by nicol3a** [comment]
Hi @umarchohan,

could you show me how you're importing `NBBottomSheet` in your Podfile? I suspect it is malformed.

It should look like this:
`pod 'NBBottomSheet', '~> 1.0'`

Thank you.

**Comment by umarchohan** [comment]
Yes it is working now.
Thanks
