### ISSUE TITLE
Doesn't resize on rotation

### ISSUE THREAD

**Issue by guidev** [nicol3a/NBBottomSheet#2]
Hi, great library. 

There's a little issue though, it doesn't seem to handle rotation.

The content view controller correctly resizes, but the sheet doesn't. 

Here's a screenshot.
![Simulator Screen Shot - iPad (6th generation) - 2020-01-05 at 22 30 10](https://user-images.githubusercontent.com/1105813/71786431-75f53880-300b-11ea-92f4-ce861d484773.png)

![Simulator Screen Shot - iPad (6th generation) - 2020-01-05 at 22 33 23](https://user-images.githubusercontent.com/1105813/71786436-80173700-300b-11ea-9c80-582e401ff2f5.png)

Thanks

**Comment by nicol3a** [comment]
Hello!

You should set the corner radius in the `viewDidLayoutSubviews` method.

There's an example of that in the sample project: https://github.com/nicol3a/NBBottomSheet/blob/master/Example/Example/Alert/AlertViewController.swift

Let me know :)

**Comment by guidev** [comment]
Solved, thanks!
