### ISSUE TITLE
How do I dismiss this sheet using dismiss(animated: , completion: )

### ISSUE THREAD

**Issue by SalilLuley** [nicol3a/NBBottomSheet#5]

**Comment by nicol3a** [comment]
Hi Salil,

the option is not available at the moment. If you want to do it, you'll have to modify the code and remove the tap gesture recognizer here:

https://github.com/nicol3a/NBBottomSheet/blob/a24783488a266ddeb18f0abc87ccd963069c4706/NBBottomSheet/NBBottomSheet/Sources/NBBottomSheetPresentationController.swift#L25-L26

**Comment by SalilLuley** [comment]
Thank you and good job ! :)
